<?php

declare(strict_types=1);

use Bambamboole\LaravelOidc\Server\Audit\LogAuditSink;
use Bambamboole\LaravelOidc\Server\Credentials\RecoveryCodeProvider;
use Bambamboole\LaravelOidc\Server\Credentials\TotpFactorProvider;
use Bambamboole\LaravelOidc\Server\Credentials\WebAuthnFactorProvider;
use Bambamboole\LaravelOidc\Server\Keys\EnvSigningKeyStore;

// Two kinds of values live here. Per-realm defaults are what ConfiguredRealm
// reads; an application with a realm model overrides them per realm through
// the Realm contract: tokens.{audiences,lifetimes}, session, scopes,
// claims_supported, keys.size, clients.{first_party,trusted,registration,
// token_exchange}, auth.{username,home,login_route,logout_redirect,
// acr_values,two_factor} and social.
// Everything else is deployment-wide: issuer, guards, key store, audit sink,
// routes.
return [
    // Identifier of the realm requests belong to outside a matched route —
    // console commands, queued jobs — and of the only realm in a single-realm
    // deployment. Bind a RealmRepository to serve realms from your own model.
    'realm' => env('OIDC_REALM', 'default'),

    'issuer' => env('OIDC_ISSUER'),

    /*
    |--------------------------------------------------------------------------
    | Signing keys
    |--------------------------------------------------------------------------
    |
    | `store` is a class-string of a SigningKeyStore implementation resolved
    | from the container. EnvSigningKeyStore reads the RS256 keypair from
    | `private_key`/`public_key` (PEM strings; \n-escaped single lines are
    | fine), falling back to oauth-{private,public}.key files under `path`,
    | and retains `additional_public_keys` for verification.
    | DatabaseSigningKeyStore keeps the keypair in `oidc_signing_keys`, where
    | every rotation retains the previous key under its own kid; it needs the
    | shipped migration.
    |
    */
    'keys' => [
        'store' => EnvSigningKeyStore::class,

        'private_key' => env('OIDC_PRIVATE_KEY'),
        'public_key' => env('OIDC_PUBLIC_KEY'),

        // Directory EnvSigningKeyStore falls back to for oauth-{private,public}.key
        // when no PEM is configured. Null means storage_path().
        'path' => env('OIDC_KEY_PATH'),

        // RSA modulus length of keys generated by oidc:rotate-keys.
        'size' => (int) env('OIDC_KEY_SIZE', 2048),

        'additional_public_keys' => array_values(array_filter([
            str_replace('\n', "\n", (string) env('OIDC_PREVIOUS_PUBLIC_KEY', '')),
        ], static fn (string $pem): bool => trim($pem) !== '')),
    ],

    'tokens' => [
        // Resource identifiers this realm serves (RFC 9068 §2.2 `aud`). An
        // access token minted without an explicit audience — authorization
        // code, refresh, session and personal access tokens — is addressed to
        // these, and the oidc guard accepts a bearer token only when its `aud`
        // names one of them or an advertised protected resource. Empty means
        // the realm issuer URL. Explicit audiences (RFC 8707 `resource` at
        // client credentials, token exchange `audience`) take precedence.
        'audiences' => [],

        'lifetimes' => [
            // Interactive access token (authorization_code) + refreshed access tokens. Short, per industry.
            'access_token' => (int) env('OIDC_ACCESS_TOKEN_TTL', 900),
            'id_token' => (int) env('OIDC_ID_TOKEN_TTL', 3600),
            // Machine-to-machine (client_credentials): no refresh, no session; client re-requests. Own TTL.
            'client_credentials' => (int) env('OIDC_M2M_ACCESS_TOKEN_TTL', 3600),
            // Idle cap on an interactive session: a refresh token unused for this long is dead.
            // The absolute cap is oidc.session.absolute_lifetime and always wins.
            'refresh_token' => (int) env('OIDC_REFRESH_TOKEN_TTL', 1209600),
        ],
    ],

    'session' => [
        'cookie_name' => env('OIDC_SESSION_COOKIE'),

        // Absolute cap on an interactive session, from login. Refresh is denied past this and the user
        // must re-authenticate; refresh-token rotation cannot extend it. Drives context.expires_at,
        // the refresh deny-check, and context pruning. The idle cap is tokens.lifetimes.refresh_token.
        'absolute_lifetime' => (int) env('OIDC_SESSION_ABSOLUTE_LIFETIME', 2592000),

        // The first-party session root token minted on login for browser-fetch.
        'token' => [
            'ttl' => (int) env('OIDC_SESSION_TOKEN_TTL', 3600),
            'session_key' => 'oidc.session_token',
            'refresh_skew' => 60,
            'scopes' => null,
            // Guard whose login/logout owns the session token. Null falls back to
            // the OIDC auth guard (oidc.auth.guard), then the application's default
            // guard; other guards never mint or revoke.
            'guard' => env('OIDC_SESSION_TOKEN_GUARD'),
        ],
    ],

    'scopes' => [
        // API scope catalog consulted by the scope repository at enumeration
        // time (consent, discovery, issuance): an inline [scope => description]
        // map, or the class-string of a ScopeCatalog implementation resolved
        // from the container. A catalog's scopes() may hit the database —
        // failures fall back to an empty catalog so key- and db-less artisan
        // runs never break; an invalid class-string fails loudly at first
        // enumeration.
        'catalog' => [],
    ],

    'claims_supported' => [
        'iss', 'sub', 'aud', 'exp', 'iat', 'auth_time', 'nonce', 'at_hash', 'azp', 'acr', 'amr', 'sid',
        'name', 'email', 'email_verified', 'locale', 'zoneinfo', 'updated_at',
    ],

    /*
    |--------------------------------------------------------------------------
    | Clients
    |--------------------------------------------------------------------------
    |
    | `first_party` names the confidential client this application uses for
    | itself: it mints the session root token and, with `trusted`, skips the
    | consent screen. `trusted` lists further client ids that skip consent.
    |
    | `registration` is RFC 7591 dynamic client registration. When enabled,
    | `POST /oauth/register` lets clients (e.g. MCP clients such as Claude or
    | Cursor) register themselves without credentials. Registered clients are
    | always public (no secret) with PKCE enforced. Redirect URIs must use
    | http(s) — hosts checked against `allowed_redirect_domains` ('*' allows
    | any) — or one of the `allowed_redirect_schemes` (e.g. 'claude', 'cursor',
    | 'vscode'; a non-http scheme requires a host). `default_scopes` restricts
    | registered clients to those scopes; empty leaves the client
    | unrestricted.
    |
    | `token_exchange` enables the RFC 8693 grant.
    |
    */
    'clients' => [
        'first_party' => [
            'client_id' => env('OIDC_FIRST_PARTY_CLIENT') ?: null,
            'trusted' => env('OIDC_FIRST_PARTY_TRUSTED', false),

            // Extra provisioning metadata applied by `oidc:install-self` on top of
            // the APP_URL-derived defaults. Token exchange is only enabled on the
            // client when at least one audience is listed.
            'provision' => [
                'redirect_uris' => [],
                'post_logout_redirect_uris' => [],
                'allowed_exchange_audiences' => [],
            ],
        ],

        'trusted' => [],

        'registration' => [
            'enabled' => env('OIDC_DCR_ENABLED', false),
            'allowed_redirect_schemes' => [],
            'allowed_redirect_domains' => ['*'],
            'default_scopes' => [],
        ],

        'token_exchange' => env('OIDC_TOKEN_EXCHANGE_ENABLED', true),
    ],

    /*
    |--------------------------------------------------------------------------
    | Audit logging
    |--------------------------------------------------------------------------
    |
    | Every security-relevant event (logins, MFA, consent, token issuance,
    | revocation, client administration) is dispatched as an AuditEvent and
    | forwarded to the configured sink. `sink` is a class-string of an
    | AuditSink implementation resolved from the container; the shipped
    | LogAuditSink writes structured log lines (failures as warning, successes
    | as info) to `log_channel`, null meaning the default channel. Recording
    | is fail-open: sink failures are reported, never propagated.
    |
    */
    'audit' => [
        'enabled' => env('OIDC_AUDIT_ENABLED', true),
        'sink' => LogAuditSink::class,
        'log_channel' => env('OIDC_AUDIT_LOG_CHANNEL'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Protected resource metadata (RFC 9728)
    |--------------------------------------------------------------------------
    |
    | Resources this provider protects, advertised via
    | `/.well-known/oauth-protected-resource/{path}`. Keys are the resource's
    | path relative to the issuer origin (no slashes); MCP clients resolve
    | their authorization server through this document. Unlisted paths 404.
    | Each advertised resource identifier is also an audience the oidc guard
    | accepts, next to tokens.audiences.
    |
    | 'mcp' => ['scopes' => ['mcp:use']],
    |
    */
    'protected_resources' => [],

    'auth' => [
        'guard' => env('OIDC_AUTH_GUARD', 'identity'),
        'provider' => env('OIDC_AUTH_PROVIDER', 'users'),
        // Guard the userinfo endpoint and resource-server routes authenticate
        // bearer tokens against. Registered with the package's driver if absent.
        'api_guard' => env('OIDC_API_GUARD', 'oidc'),
        'home' => env('OIDC_AUTH_HOME', '/dashboard'),
        'username' => env('OIDC_AUTH_USERNAME', 'email'),
        // Route name or path the authorize endpoint sends anonymous users to.
        'login_route' => env('OIDC_LOGIN_ROUTE', 'login'),
        // Where end-session lands without a post_logout_redirect_uri.
        'logout_redirect' => '/',
        // The `acr` claim (OIDC Core §2) an authentication earns: one method
        // in `amr` reports single_factor, two or more report multi_factor.
        // Substitute URIs or RFC 6711 names your relying parties expect; both
        // are advertised as acr_values_supported.
        'acr_values' => [
            'single_factor' => '1',
            'multi_factor' => '2',
        ],
        'two_factor' => [
            'challenge_providers' => ['totp', 'webauthn'],
            'secret_length' => 16,
            'window' => 1,
            'recovery_codes' => 8,
        ],
        'factors' => [
            TotpFactorProvider::class,
            RecoveryCodeProvider::class,
            WebAuthnFactorProvider::class,
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Social login
    |--------------------------------------------------------------------------
    |
    | Upstream identity providers users can authenticate with. A provider is
    | active only when its client_id is configured. `driver` selects the
    | implementation: google, apple, github, or the generic `oidc` driver for
    | any OIDC-compliant IdP (requires `issuer`). Register custom drivers via
    | Oidc::extendSocialProvider().
    |
    */
    'social' => [
        // Attach an upstream identity to an existing local user when the
        // provider reports a verified email that matches.
        'link_by_verified_email' => true,
        // Create a local user on first social login via the action registered
        // with Oidc::createUsersFromSocialUsing(). Without a registered
        // action, provisioning is effectively disabled.
        'auto_provision' => true,
        'providers' => [
            'google' => [
                'driver' => 'google',
                'client_id' => env('OIDC_SOCIAL_GOOGLE_CLIENT_ID'),
                'client_secret' => env('OIDC_SOCIAL_GOOGLE_CLIENT_SECRET'),
            ],
            'apple' => [
                'driver' => 'apple',
                'client_id' => env('OIDC_SOCIAL_APPLE_CLIENT_ID'),
                'team_id' => env('OIDC_SOCIAL_APPLE_TEAM_ID'),
                'key_id' => env('OIDC_SOCIAL_APPLE_KEY_ID'),
                'private_key' => env('OIDC_SOCIAL_APPLE_PRIVATE_KEY'),
            ],
            'github' => [
                'driver' => 'github',
                'client_id' => env('OIDC_SOCIAL_GITHUB_CLIENT_ID'),
                'client_secret' => env('OIDC_SOCIAL_GITHUB_CLIENT_SECRET'),
            ],
        ],
    ],

    'routes' => [
        'middleware' => [],

        // `single` serves the configured realm from the application root, so the
        // issuer is the bare origin and provider and application share one
        // session. `path` serves every realm below /realms/{realm} with its own
        // issuer and its own session cookie — required for more than one realm
        // per deployment.
        'realms' => env('OIDC_ROUTE_REALMS', 'single'),
    ],
];
